version: '3.8'
services:
  ubervet-database-mongo-container:
    container_name: ubervet-database-mongo-container
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    restart: always
      #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
    #MONGO_INITDB_ROOT_PASSWORD: example